version: "1"
steps:
  - name: test
    image: alpine:latest
    commands:
      - echo "hello"
      
 - name: fake log
   image: golang:latest
   commands:
     - go install github.com/mingrammer/flog@latest
     - flog -t stdout -f json -b 25000000 -d 1ms
