version: "1"

services:
  - name: mysql
    image: mysql:5.7.24

  - name: redis
    image: redis:alpine

steps:
  - name: go
    image: golang:1.13
    environment:
      CGO_ENABLED: '0'
      GOOS: linux
    commands:
      - go get ./...
      - go test ./...

  - name: node
    image: amd64/node:10.24.1@sha256:686e0e859358f28bfe1641e1627549b9cd0ad74f222b953d74209213488c6858
    commands:
      - npm install
      - npm test

secrets:
  # Implicit secret definition.
  - name: vault_token

  - origin:
      name: private vault
      image: target/secret-vault:v0.1.0
      secrets: [ vault_token ]
      parameters:
        addr: vault.example.com
        auth_method: token
        username: octocat
        items:
          - source: secret/docker
            path: docker
