version: "1"

services:
  - name: mysql
    image: mysql:5.7.24

  - name: redis
    image: redis:alpine

steps:
  - name: go
    image: golang:1.13
    environment:
      CGO_ENABLED: '0'
      GOOS: linux
    commands:
      - go get ./...
      - go test ./...

  - name: node
    image: amd64/node:17.8.0@sha256:9f554c9a505d5b00316fdac324ba188f80a631084d04d0f6f6c1a906e6ee588e
    commands:
      - npm install
      - npm test

secrets:
  # Implicit secret definition.
  - name: vault_token

  - origin:
      name: private vault
      image: target/secret-vault:v0.0.9
      secrets: [ vault_token ]
      parameters:
        addr: vault.example.com
        auth_method: token
        username: octocat
        items:
          - source: secret/docker
            path: docker
