# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node16:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug info
        run: |
          docker version --format '{{.Server.Version}}'
          docker compose version --short

      - name: build image
        run: |
          docker buildx build -t localserver --build-arg="node_ver=16" --load .

      - name: run image before
        run: |
          docker network create vela
          docker run --network=vela localserver

      - name: other info
        run: |
          cat /etc/hosts
          cat /etc/gai.conf
          sudo echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - name: run image
        run: |
          docker run --network=vela localserver

  node18:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug info
        run: |
          docker version --format '{{.Server.Version}}'
          docker compose version --short

      - name: build image
        run: |
          docker buildx build -t localserver --build-arg="node_ver=18" --load .

      - name: run image before
        run: |
          docker network create vela
          docker run --network=vela localserver

      - name: other info
        run: |
          cat /etc/hosts
          cat /etc/gai.conf
          sudo echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - name: run image
        run: |
          docker run --network=vela localserver

  node20:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug info
        run: |
          docker version --format '{{.Server.Version}}'
          docker compose version --short

      - name: build image
        run: |
          docker buildx build -t localserver --build-arg="node_ver=20" --load .

      - name: run image before
        run: |
          docker network create vela
          docker run --network=vela localserver

      - name: other info
        run: |
          cat /etc/hosts
          cat /etc/gai.conf
          sudo echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - name: run image
        run: |
          docker run --network=vela localserver

  node22:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug info
        run: |
          docker version --format '{{.Server.Version}}'
          docker compose version --short

      - name: build image
        run: |
          docker buildx build -t localserver --build-arg="node_ver=22" --load .

      - name: run image after
        run: |
          docker network create vela
          docker run --network=vela localserver

      - name: other info
        run: |
          cat /etc/hosts
          cat /etc/gai.conf
          sudo echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - name: run image
        run: |
          docker run --network=vela localserver
